export const offices = [
  {
    id: 1,
    title: "Headquarter",
    city: "Texas, USA",
    address: "17250 Dallas Pkwy Dallas, TX 75248, USA",
    phone: "+1 469 793 9837",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/texas_usa_office_iq.png",
  },
  {
    id: 2,
    title: "",
    city: "New York, USA",
    address: "349 5th Ave, New York, NY 10016, USA",
    phone: "+1 917 477 8991",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/newyork-office-icn.png",
  },
  {
    id: 3,
    title: "Branch",
    city: "Toronto, Canada",
    address: "502-10 Markbrook Lane, Etobicoke, M9V5E3",
    phone: "+1 647 637 9108",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/canada-office-icn.png",
  },
  {
    id: 4,
    title: "",
    city: "London",
    address: "133 Preston Hill, Harrow HA3 9XE, London",
    phone: "",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/london-office-icn.png",
  },
  {
    id: 5,
    title: "",
    city: "Australia",
    address: "19 Burns Ave, Clayton South VIC 3169, Australia",
    phone: "",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/australia-office-icn.png",
  },
  {
    id: 6,
    title: "",
    city: "California, USA",
    address: "2976 Casa Nueva Ct, San Jose, CA 95124, USA",
    phone: "",
    image: "https://www.iqlance.com/wp-content/themes/iqlance/img/california.png",
  },
];